// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: teerpc.proto

#include "teerpc.pb.h"
#include "teerpc.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace teerpc {

static const char* TeeComputor_method_names[] = {
  "/teerpc.TeeComputor/execute",
};

std::unique_ptr< TeeComputor::Stub> TeeComputor::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< TeeComputor::Stub> stub(new TeeComputor::Stub(channel));
  return stub;
}

TeeComputor::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_execute_(TeeComputor_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status TeeComputor::Stub::execute(::grpc::ClientContext* context, const ::teerpc::TaskRequest& request, ::teerpc::TaskReply* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_execute_, context, request, response);
}

void TeeComputor::Stub::experimental_async::execute(::grpc::ClientContext* context, const ::teerpc::TaskRequest* request, ::teerpc::TaskReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_execute_, context, request, response, std::move(f));
}

void TeeComputor::Stub::experimental_async::execute(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::teerpc::TaskReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_execute_, context, request, response, std::move(f));
}

void TeeComputor::Stub::experimental_async::execute(::grpc::ClientContext* context, const ::teerpc::TaskRequest* request, ::teerpc::TaskReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_execute_, context, request, response, reactor);
}

void TeeComputor::Stub::experimental_async::execute(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::teerpc::TaskReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_execute_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::teerpc::TaskReply>* TeeComputor::Stub::AsyncexecuteRaw(::grpc::ClientContext* context, const ::teerpc::TaskRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::teerpc::TaskReply>::Create(channel_.get(), cq, rpcmethod_execute_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::teerpc::TaskReply>* TeeComputor::Stub::PrepareAsyncexecuteRaw(::grpc::ClientContext* context, const ::teerpc::TaskRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::teerpc::TaskReply>::Create(channel_.get(), cq, rpcmethod_execute_, context, request, false);
}

TeeComputor::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TeeComputor_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TeeComputor::Service, ::teerpc::TaskRequest, ::teerpc::TaskReply>(
          std::mem_fn(&TeeComputor::Service::execute), this)));
}

TeeComputor::Service::~Service() {
}

::grpc::Status TeeComputor::Service::execute(::grpc::ServerContext* context, const ::teerpc::TaskRequest* request, ::teerpc::TaskReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace teerpc

